version: '3.8'

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.9.2
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__SECRET_KEY: 'cok_gizli_bir_anahtar_123'
    _PIP_ADDITIONAL_REQUIREMENTS: 'pandas google-generativeai jinja2 psycopg2-binary'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./scripts:/opt/airflow/scripts
    - ./templates:/opt/airflow/templates

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow 
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      # tüm tablolar, veritabanı dosyaları ve kullanıcı şifreleri vs. iki noktanin sagina yazar, bu bilgileri ben
      #  bilgisayarimda olusturdugum postgres-db-volume de saklamaya baslarim bu sayede variables eklentilerim kaybolmaz.
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    depends_on:
      - postgres

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - airflow-init

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - postgres
      - airflow-init
#docker ayaga kalkarken postgres-db-volume --->  /var/lib/postgresql/data  mount edilir(baglanir birbirine)
volumes:
  postgres-db-volume: